### ISSUE TITLE
Container runs out of memory

### ISSUE THREAD

**Issue by ds0nt** [atcol/docker-registry-ui#172]
Is it normal that this container blows through 500mi limits on startup?

```
      - name: registry-ui
        image: atcol/docker-registry-ui
        ports:
        - name: http-ui
          containerPort: 8080
        env:
        - name: REG1
          value: http://registry:8080/v1/
        - name: READ_ONLY
          value: "true"
        resources:
          requests:
            memory: 250Mi
            cpu: 250m
          limits:
            memory: 500Mi
            cpu: 500m
```
