### ISSUE TITLE
Cannot connect to a registry using self signed REGISTRY_HTTP_TLS_CERTIFICATE

### ISSUE THREAD

**Issue by sebastianzillessen** [atcol/docker-registry-ui#175]
My Registry (running on a docker container in the same swarm setup) is configured as follows:
```
 registry:
    image: registry:2.6.2
    ports:
      - 5000:5000
    environment:
      - REGISTRY_LOG_LEVEL=info
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/
      - REGISTRY_HTTP_TLS_KEY=/certs/
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    networks:
      - registry-network

  registry-ui:
    image: atcol/docker-registry-ui
    environment:
      - VIRTUAL_HOST=registry-ui.*
      - REG1=https://registry:5000/v2/
      #- READ_ONLY=false
    networks:
      - registry-network
```

If the docker-registry-ui tries to connect without https enabled I see the following log:

```
2019/09/14 11:26:03 http: TLS handshake error from 10.0.22.4:46318: tls: first record does not look like a TLS handshake
```

If I use https I see:
```
2019/09/14 11:26:39 http: TLS handshake error from 10.0.22.4:46448: remote error: tls: unknown certificate
```

Any idea on how to fix this? 
Thanks!
